### PR TITLE
bug: show the number of rows in the footer 

### LINKED ISSUE #461: bug(table): show the number of rows in the footer
When we provide the row number of the table it does not show on the footer, the footer is fixed to 10. 
make the footer update and add a story with multiple pages (20 dummy data)

image

### PR DESCRIPTION
**Pull request by KaisAlHusrom**
## Description

Add pagination to the footer of table, 
make sure the data displays based on the page correctly
add options to change rows per page

### Before:
image
### After:
image

## Types of changes

- [ ] Chore (non-breaking change which improve code)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] Added story.
- [x] Checked relative components.
- [ ] Checked the component on production.
- [ ] Added related docs.

Close #461

### CODE REVIEW

File: src/molecules/tables/index.tsx [hunk 1]
```diff
@@ -236,32 +241,38 @@ export default function DataTable<TData, TValue>(
...
-                      <TableCell colSpan={row.getVisibleCells().length}>
-                        {renderSubComponent({ row })}
-                      </TableCell>
+              table
+                .getRowModel()
+                .rows.slice(
+                  pagination.pageIndex * pagination.pageSize,
+                  (pagination.pageIndex + 1) * pagination.pageSize
+                )
+                .map((row) => (
```
[the remark this answers is not in the document]
Comment (KaisAlHusrom) [reply src/molecules/tables/index.tsx:250]: To display only the rows of the selected page, previously, all rows were shown regardless of the page number or rows per page count.

File: src/molecules/tables/index.tsx [hunk 2]
```diff
@@ -136,6 +139,7 @@ export default function DataTable<TData, TValue>(
     onSortingChange: setSorting,
     getCoreRowModel: getCoreRowModel(),
     manualPagination: true,
+    onPaginationChange: setPagination,
```
[the remark this answers is not in the document]
Comment (KaisAlHusrom) [reply src/molecules/tables/index.tsx:142]: You’re right, it wasn’t necessary. I’ll rewrite the code and push it again without the custom pagination state.

**Comment by KaisAlHusrom** [comment]
I merged the branch with the current main branch to resolve conflicts. Please let me know if I missed anything or made any mistakes.

File: src/molecules/tables/index.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (a0m0rajab) [reply src/molecules/tables/index.tsx]: Thanks for the comment, I just double checked the code, this issue is happening since we are setting ManualPagination to true in the code. If we set it to false we do not need such code. I am going to share few comments about the code and can accept it after it's being applied.

File: src/molecules/tables/index.tsx [hunk 3]
```diff
@@ -244,37 +244,45 @@ export default function DataTable<TData, TValue>(
...
-                      <TableCell colSpan={row.getVisibleCells().length}>
-                        {renderSubComponent({ row })}
-                      </TableCell>
+              table
+                .getRowModel()
+                .rows.slice(
+                  table.getState().pagination.pageIndex *
+                    table.getState().pagination.pageSize,
+                  (table.getState().pagination.pageIndex + 1) *
+                    table.getState().pagination.pageSize
```
Comment (a0m0rajab) [inline src/molecules/tables/index.tsx:253]: Let's remove the slice here and set the [maual-pagination](https://tanstack.com/table/latest/docs/api/features/pagination#manualpagination) to false in the table props, to handle the server side request we have a function called fetch request if it's there we can set it to false.

**Review by a0m0rajab — COMMENTED** [review]
Thanks for the fix, let's just have one final change for this to accept it. 
it would be great to have the fetchrequest set for the manual pagination. 

```js
    manualFiltering:  typeof fetchRequest === "function" ?  true : false,
```

File: src/molecules/tables/index.tsx (hunk 3 above)
Comment (KaisAlHusrom) [reply src/molecules/tables/index.tsx:253]: I removed the slice function and updated manualPagination as shown below:
image

However, all rows are still displayed, ignoring the page number and rows-per-page states.
example:
image

I also tried setting manualPagination to false without checking for fetchRequest (since fetchRequest is undefined here), but the issue persists.

Let me know if you’d like me to push these changes regardless of this problem.

Comment (a0m0rajab) [reply src/molecules/tables/index.tsx:253]: Checking [tanstack example](https://tanstack.com/table/latest/docs/framework/react/examples/pagination) I relized that we miss a function, if you add the `getPaginationRowModel` then it should work as expected.

```diff
+    getPaginationRowModel: getPaginationRowModel(),
+    manualPagination: false,
```

Comment (KaisAlHusrom) [reply src/molecules/tables/index.tsx]: I added it and now it works.

**Review by a0m0rajab — APPROVED** [review]
Thanks for your PR, it looks great!
